# Generated by Django 5.1.7 on 2025-03-15 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_evaluation', models.CharField(max_length=50)),
                ('developpement', models.TextField()),
                ('description', models.TextField()),
                ('date_creation', models.DateField()),
                ('date_limite', models.DateField()),
                ('correction', models.TextField()),
                ('bareme', models.FloatField()),
                ('support', models.FileField(upload_to='evaluations/')),
                ('enseignant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.enseignant')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
        migrations.CreateModel(
            name='EtudiantEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.etudiant')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluation')),
            ],
            options={
                'verbose_name': 'Étudiant évaluation',
                'verbose_name_plural': 'Étudiants évaluations',
            },
        ),
    ]
