# Generated by Django 5.1.7 on 2025-03-15 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RapportFinancier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_rapport', models.CharField(max_length=50)),
                ('annee', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('beneficiaires', models.TextField()),
            ],
            options={
                'verbose_name': 'Rapport financier',
                'verbose_name_plural': 'Rapports financiers',
            },
        ),
        migrations.CreateModel(
            name='Comptable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('rapport_financier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiement.rapportfinancier')),
            ],
            options={
                'verbose_name': 'Comptable',
                'verbose_name_plural': 'Comptables',
            },
        ),
    ]
