# Generated by Django 5.1.7 on 2025-03-15 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('annee_academique', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('effectif', models.IntegerField()),
                ('filiere', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=50)),
                ('volume_horaire', models.IntegerField()),
                ('description', models.TextField()),
                ('objectif', models.TextField()),
                ('support', models.FileField(upload_to='cours/')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('filiere', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='CoursEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.cours')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.enseignant')),
            ],
            options={
                'verbose_name': 'Cours enseignant',
                'verbose_name_plural': 'Cours enseignants',
            },
        ),
        migrations.CreateModel(
            name='CoursEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.etudiant')),
            ],
            options={
                'verbose_name': 'Cours étudiant',
                'verbose_name_plural': 'Cours étudiants',
            },
        ),
        migrations.CreateModel(
            name='EtudiantClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.etudiant')),
            ],
            options={
                'verbose_name': 'Étudiant classe',
                'verbose_name_plural': 'Étudiants classes',
            },
        ),
        migrations.CreateModel(
            name='EnseignantMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.matiere')),
            ],
            options={
                'verbose_name': 'Enseignant matière',
                'verbose_name_plural': 'Enseignants matières',
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.matiere'),
        ),
        migrations.CreateModel(
            name='Planifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(max_length=50)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.enseignant')),
            ],
            options={
                'verbose_name': 'Planification',
                'verbose_name_plural': 'Planifications',
            },
        ),
    ]
